from time import sleep

print("")
print("")
print("      WELCOME TO THE GUESSING GAME")
print("")
print("")
sleep (.2)
print("This game is simple...")
sleep (.2)
print("")
print(" - I generate a number")
sleep (.2)
print(" - You have to try to guess it")
sleep (.2)
print(" - I will guide you by telling you if the number is too high or too low")
sleep (.2)
print("")
print("Godspeed!")
print("")
sleep (.2)