from time import sleep

print("")
print("      WELCOME TO THE GUESSING GAME")
print("")
print("")
sleep (2)
print("The game is simple...")
print("")
print(" - I generate a number")
sleep (1)
print(" - You have to try to guess it")
sleep (1)
print(" - I will guide you by telling you if the number is too high or too low")
sleep (1)
print("")
sleep (2)
print("Godspeed!")
sleep (2)
print("")